<a href="https://colab.research.google.com/github/prasanna-venkatesh-m/neural_network_from_scratch/blob/main/neural_network_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [84]:
df = pd.read_csv('/content/Position_Salaries.csv');
df = df.drop(columns=['Position'])

In [85]:
X = df['Level'].to_frame()
y = df['Salary'].to_frame()

In [86]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [87]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [88]:
X_np = x_sc.fit_transform(X_train)  # converts DataFrame to numpy array
y_np = y_sc.fit_transform(y_train)  # same for target

In [89]:
layer1 = 16
W1 = np.random.rand(X.shape[1],layer1)
b1 = np.random.rand(layer1,)

layer2 = 1
W2 = np.random.rand(layer1, layer2)
b2 = np.random.rand(layer2,)

epoch = 2000
learning_rate = 0.01

In [90]:
print(W1)
print(b1)
print(W2)
print(b2)

[[0.66983579 0.36090626 0.15496674 0.74944036 0.31438423 0.94274349
  0.18914133 0.7892951  0.11389462 0.98657574 0.76047876 0.12194416
  0.896165   0.59611929 0.82264968 0.77234892]]
[0.37681213 0.98292622 0.41526823 0.5917299  0.9532096  0.02713239
 0.76726145 0.44806015 0.62799525 0.86735039 0.90964951 0.50954502
 0.84343071 0.50189391 0.77513844 0.52297574]
[[0.68516268]
 [0.27576709]
 [0.85898679]
 [0.09827679]
 [0.8505695 ]
 [0.7028113 ]
 [0.1032489 ]
 [0.11610483]
 [0.39579862]
 [0.3371157 ]
 [0.67358498]
 [0.83698652]
 [0.59001654]
 [0.11338284]
 [0.15226073]
 [0.20124327]]
[0.08869831]


In [91]:
def relu(Z):
  return np.maximum(0, Z)

In [92]:
def relu_derivative(Z):
  return Z > 0

In [93]:
def forward_pass(X, W1, b1, W2, b2):

  # Layer 1
  Z1 = np.dot(X, W1) + b1 #X (m,n) W1(n,16) result(m,16)
  A1 = relu(Z1) #result (m,16)

  # Layer 2
  Z2 = np.dot(A1, W2) + b2 #Z1(m,16) W2(16,1) result(m,1)

  return Z1, A1, Z2

In [94]:
def loss_function(y, y_pred):
  return mean_squared_error(y, y_pred)

In [95]:
def backward_pass(X,y, Z1, A1, Z2, W2):
  m = X.shape[0]

  dZ2 = (2 / m) * (Z2 - y) #z2(m,1) y(m,1) result(m,1)
  dW2 = np.dot(A1.T, dZ2) #z1(n,16) dz2(m,1) so(16,n)*(m,1) result(16,1)
  db2 = np.sum(dZ2, axis=0) #dz2 (m,1) result(1,)

  dA1 = np.dot(dZ2, W2.T) #dZ2(m,1) W2(16,1) so(m,1)*(1,16) result(m,16)
  dZ1 = dA1 * relu_derivative(Z1) #dA1(m,16) Z1(m,16) result(m,16)
  dW1 = np.dot(X.T, dZ1) #X(m,n) dz1(m,16) so(n,m)*(m,16) result(n,16)
  db1 = np.sum(dZ1, axis=0) #dz1(m,16) result(16,)

  return dW1, db1, dW2, db2

In [96]:
for i in range(epoch):
  Z1, A1, Z2 = forward_pass(X_np, W1, b1, W2, b2)
  loss = loss_function(y_np, Z2)

  dw1, db1, dw2, db2 = backward_pass(X_np,y_np, Z1, A1, Z2, W2)

  W1 -= learning_rate * dw1
  b1 -= learning_rate * db1
  W2 -= learning_rate * dw2
  b2 -= learning_rate * db2

  print(f'Epoch: {i} Loss: {loss}')

Epoch: 0 Loss: 28.651539723500683
Epoch: 1 Loss: 12.913932709280333
Epoch: 2 Loss: 6.649891795229303
Epoch: 3 Loss: 3.7342086582034018
Epoch: 4 Loss: 2.2692324480524273
Epoch: 5 Loss: 1.4975384770007887
Epoch: 6 Loss: 1.0755825670426944
Epoch: 7 Loss: 0.8359385909617834
Epoch: 8 Loss: 0.693543221175074
Epoch: 9 Loss: 0.6072211850683158
Epoch: 10 Loss: 0.5496050094388306
Epoch: 11 Loss: 0.5082043424766731
Epoch: 12 Loss: 0.4762715909282421
Epoch: 13 Loss: 0.4501253184714096
Epoch: 14 Loss: 0.4277314129102484
Epoch: 15 Loss: 0.4079454892086386
Epoch: 16 Loss: 0.39020220366214314
Epoch: 17 Loss: 0.37487360048633556
Epoch: 18 Loss: 0.36068499137369314
Epoch: 19 Loss: 0.3474894338627579
Epoch: 20 Loss: 0.33518195798902556
Epoch: 21 Loss: 0.323682181420775
Epoch: 22 Loss: 0.3133466857921675
Epoch: 23 Loss: 0.30397113665129216
Epoch: 24 Loss: 0.2951150961960501
Epoch: 25 Loss: 0.2867470820297287
Epoch: 26 Loss: 0.2788382966983991
Epoch: 27 Loss: 0.27136210286217705
Epoch: 28 Loss: 0.264293690

In [97]:
print(W1)
print(b1)
print(W2)
print(b2)

[[0.76166505 0.31172237 0.50454484 0.71289654 0.36704564 1.08006049
  0.1320174  0.76446955 0.11703384 0.94817703 0.76777464 0.37478651
  0.88281812 0.567521   0.7792611  0.74872934]]
[-0.23419352  0.96748891 -0.46832728  0.63250161  0.61085794 -0.91455215
  0.81585101  0.46538154  0.49478706  0.82717442  0.67565586 -0.34804755
  0.66775049  0.52021021  0.80908155  0.50555364]
[[ 0.71657023]
 [-0.1886088 ]
 [ 1.00115863]
 [-0.14729921]
 [ 0.47917782]
 [ 1.26729429]
 [-0.287877  ]
 [-0.0529541 ]
 [ 0.11486935]
 [-0.00765625]
 [ 0.33486143]
 [ 0.82281129]
 [ 0.28207262]
 [-0.09377216]
 [-0.1743788 ]
 [ 0.00295752]]
[-0.44404863]


In [98]:
def predict(X_pred):
  X_scaled = x_sc.transform(X_pred)
  _, _, Z2 = forward_pass(X_scaled, W1, b1, W2, b2)
  return y_sc.inverse_transform(Z2)

In [99]:
result = predict(X_test)
print(result)

[[655671.40058934]
 [ 55642.9350338 ]]


In [103]:
print(mean_squared_error(y_test, result))
print(r2_score(y_test, result))

12132713838.620598
0.7603414550395932


In [105]:
_, _, train_pred = forward_pass(X_np, W1, b1, W2, b2)
print(mean_squared_error(y_train, y_sc.inverse_transform(train_pred)))
print(r2_score(y_train, y_sc.inverse_transform(train_pred)))

147349892.87312102
0.9983249671368204
